/**
 * Loads the AY26/27 robot build lists (data/Calibur_AY2627.xlsx) as ONE SQL
 * transaction. The cleaning rules live in scripts/build-lists/rules.ts.
 *
 *   npx tsx scripts/import-build-lists.ts [--schema public|test] [--rehearse]
 *
 * writes data/clean/build-lists[.test][.rehearse].sql. A --rehearse file ends
 * in `raise exception` with the row counts, so running it changes nothing.
 * Apply with:
 *
 *   supabase db query --linked -f data/clean/build-lists.sql
 *
 * Re-runnable: it replaces the season's build lists by name, and touches
 * nothing else -- no products, no stock, no review items.
 *
 * This script never connects to a database.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import ExcelJS from "exceljs";

import { sqlText } from "./import-clean-data";
import { cellText } from "./clean-data/sources";
import {
  BUILD_SHEETS,
  type BuildLine,
  expectedProductNames,
  parseBuildSheet,
  SEASON,
  type SheetRow,
  WORKBOOK,
} from "./build-lists/rules";

export const XLSX_PATH = `data/${WORKBOOK}`;
const OUT_DIR = "data/clean";
const COLUMNS = 10; // A..J

export interface BuildListPlan {
  name: string;
  sheet: string;
  lines: BuildLine[];
}

async function readSheets(file: string): Promise<{ plans: BuildListPlan[]; warnings: string[] }> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(file);
  const plans: BuildListPlan[] = [];
  const warnings: string[] = [];
  for (const { sheet, name } of BUILD_SHEETS) {
    const ws = workbook.getWorksheet(sheet);
    if (!ws) throw new Error(`${file}: sheet "${sheet}" not found`);
    const rows: SheetRow[] = [];
    for (let r = 1; r <= ws.rowCount; r++) {
      const row = ws.getRow(r);
      const cells = Array.from({ length: COLUMNS }, (_, i) => cellText(row.getCell(i + 1).value));
      if (cells.some((c) => c !== "")) rows.push({ row: r, cells });
    }
    const parsed = parseBuildSheet(sheet, rows);
    plans.push({ name, sheet, lines: parsed.lines });
    warnings.push(...parsed.warnings);
  }
  return { plans, warnings };
}

const num = (value: number | null) => (value === null ? "null" : String(value));

export function buildSql(plans: BuildListPlan[], options: { schema: "public" | "test"; rehearse: boolean }): string {
  const { schema, rehearse } = options;
  const names = plans.map((p) => sqlText(p.name)).join(", ");
  const products = expectedProductNames().map((n) => sqlText(n)).join(", ");

  const sql: string[] = [
    `-- Generated by scripts/import-build-lists.ts from ${XLSX_PATH} for the "${schema}" schema. Regenerate rather than edit.`,
    "-- One transaction: all of it lands, or none of it.",
    "begin;",
    `set local search_path = ${schema};`,
    "",
    "do $$",
    "declare v_missing text;",
    "begin",
    `  if to_regclass('${schema}.build_list_lines') is null then`,
    `    raise exception 'migration 0027 is not applied to the ${schema} schema';`,
    "  end if;",
    "  -- Every product the rules link to must exist exactly once, by name.",
    "  select string_agg(n, ', ') into v_missing",
    `  from unnest(array[${products}]::text[]) n`,
    "  where (select count(*) from products p where p.name = n) <> 1;",
    "  if v_missing is not null then",
    "    raise exception 'products missing or not unique: %', v_missing;",
    "  end if;",
    "end $$;",
    "",
    `delete from build_lists where season = ${sqlText(SEASON)} and name in (${names});`,
  ];

  for (const plan of plans) {
    const list = `(select id from build_lists where season = ${sqlText(SEASON)} and name = ${sqlText(plan.name)})`;
    sql.push(
      "",
      `-- ${plan.sheet}: ${plan.lines.length} lines`,
      "insert into build_lists (season, name, source) values " +
        `(${sqlText(SEASON)}, ${sqlText(plan.name)}, ${sqlText(`${WORKBOOK} > ${plan.sheet}`)});`,
    );
    if (!plan.lines.length) continue;
    const rows = plan.lines.map((l) =>
      [
        list,
        l.position,
        sqlText(l.section),
        sqlText(l.category),
        sqlText(l.partName),
        l.productName ? `(select id from products where name = ${sqlText(l.productName)})` : "null",
        num(l.qty),
        sqlText(l.sourcing),
        num(l.unitPriceSgd),
        sqlText(l.supplier),
        sqlText(l.supplierUrl),
        sqlText(l.notes),
        sqlText(l.sourceText),
        l.sourceRow,
      ].join(", "),
    );
    sql.push(
      "insert into build_list_lines (build_list_id, position, section, category, part_name, product_id, qty, " +
        "sourcing, unit_price_sgd, supplier, supplier_url, notes, source_text, source_row) values",
      rows.map((r) => `  (${r})`).join(",\n") + ";",
    );
  }

  const report = [
    "  select format('build_lists=%s lines=%s linked_to_product=%s referee_kit=%s est_cost_sgd=%s',",
    `    (select count(*) from build_lists where season = ${sqlText(SEASON)}),`,
    `    (select count(*) from build_list_lines l join build_lists b on b.id = l.build_list_id where b.season = ${sqlText(SEASON)}),`,
    `    (select count(*) from build_list_lines l join build_lists b on b.id = l.build_list_id where b.season = ${sqlText(SEASON)} and l.product_id is not null),`,
    `    (select count(*) from build_list_lines l join build_lists b on b.id = l.build_list_id where b.season = ${sqlText(SEASON)} and l.sourcing = 'referee_kit'),`,
    `    (select coalesce(sum(l.qty * l.unit_price_sgd), 0) from build_list_lines l join build_lists b on b.id = l.build_list_id where b.season = ${sqlText(SEASON)})`,
    "  ) into v_report;",
  ];
  sql.push("", "do $$", "declare v_report text;", "begin", ...report);
  if (rehearse) {
    sql.push("  raise exception 'BUILD LISTS REHEARSAL OK, rolled back: %', v_report;", "end $$;");
  } else {
    sql.push("  raise notice 'build lists loaded: %', v_report;", "end $$;", "", "commit;");
  }
  return sql.join("\n") + "\n";
}

const isMain = (() => {
  if (!process.argv[1]) return false;
  try {
    return fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
  } catch {
    return false;
  }
})();

if (isMain) {
  const rehearse = process.argv.includes("--rehearse");
  const schema = process.argv.includes("--schema") ? process.argv[process.argv.indexOf("--schema") + 1] : "public";
  if (schema !== "public" && schema !== "test") {
    console.error('--schema must be "public" or "test".');
    process.exit(1);
  }

  readSheets(XLSX_PATH).then(({ plans, warnings }) => {
    for (const warning of warnings) console.warn(`warning: ${warning}`);
    const out = path.join(OUT_DIR, `build-lists${schema === "test" ? ".test" : ""}${rehearse ? ".rehearse" : ""}.sql`);
    writeFileSync(out, buildSql(plans, { schema, rehearse }), "utf-8");
    for (const plan of plans) {
      const linked = plan.lines.filter((l) => l.productName).length;
      const cost = plan.lines.reduce((sum, l) => sum + (l.qty ?? 0) * (l.unitPriceSgd ?? 0), 0);
      console.log(`${plan.name.padEnd(22)} ${String(plan.lines.length).padStart(3)} lines, ${linked} linked, est. S$${cost.toFixed(2)}`);
    }
    console.log(`\nWrote ${out} (${warnings.length} warning(s)).`);
    console.log(
      rehearse
        ? `Rehearse (always rolls back): supabase db query --linked -f ${out}`
        : `Apply: supabase db query --linked -f ${out}`,
    );
  });
}
