-- Self-service onboarding with admin-issued join codes.
--
-- An admin mints a short code that is valid for N uses within M minutes and
-- shows it (or its QR) to the people in the room. Each of them opens the
-- Mini App, enters the code, their name and email, and accepts the PDPA
-- notice; join_with_code() then links their Telegram account in one
-- transaction. This replaces "import the roster, hope the handles match,
-- clear the bind queue" as the normal path; the roster import and the bind
-- queue remain for the cases a code does not cover.
--
-- Every attempt, successful or not, is logged in join_code_attempts. The
-- use-count limit only bounds a leaked code; the log is what shows one
-- (attempts after a code closed, or more people than were in the room).

-- ---------------------------------------------------------------------------
-- members: how and when they joined
-- ---------------------------------------------------------------------------

alter table members add column notice_accepted_at timestamptz;
alter table members add column join_code_id uuid;

-- ---------------------------------------------------------------------------
-- join_codes
-- ---------------------------------------------------------------------------

create table join_codes (
  id          uuid primary key default gen_random_uuid(),
  -- 8 characters, uppercase letters and digits minus the ambiguous 0/O/1/I/L.
  -- Generated by the admin page (src/lib/join/code.ts); typed case-insensitively.
  code        text not null unique,
  max_uses    int not null,
  used_count  int not null default 0,
  valid_minutes int not null,
  -- Set by the insert trigger from valid_minutes and the DATABASE clock, so a
  -- skewed admin laptop cannot mint a code that is already dead or lives on.
  expires_at  timestamptz not null,
  revoked_at  timestamptz,
  note        text,
  created_by  uuid references members(id),
  created_at  timestamptz not null default now(),
  constraint join_codes_code_shape check (code ~ '^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{8}$'),
  constraint join_codes_max_uses_range check (max_uses between 1 and 500),
  constraint join_codes_used_count_range check (used_count between 0 and max_uses),
  constraint join_codes_valid_minutes_range check (valid_minutes between 1 and 10080)
);

alter table members
  add constraint members_join_code_id_fkey foreign key (join_code_id) references join_codes(id);

-- Who minted it is stamped from the session, never taken from the client.
create or replace function join_codes_stamp_creator()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.created_by := (select m.id from members m where m.nus_email = auth.email() and m.active);
  new.created_at := now();
  new.used_count := 0;
  new.expires_at := now() + make_interval(mins => new.valid_minutes);
  return new;
end;
$$;

revoke execute on function join_codes_stamp_creator() from public, anon;

create trigger join_codes_stamp_creator
before insert on join_codes
for each row execute function join_codes_stamp_creator();

-- Admin-only. No DELETE policy: a revoked code stays for the audit trail.
alter table join_codes enable row level security;
create policy join_codes_admin_select on join_codes
  for select using (is_admin());
create policy join_codes_admin_insert on join_codes
  for insert with check (is_admin());
create policy join_codes_admin_update on join_codes
  for update using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------------
-- join_code_attempts
-- ---------------------------------------------------------------------------

create table join_code_attempts (
  id                 bigserial primary key,
  join_code_id       uuid references join_codes(id),
  -- What was typed, normalised. Kept for unknown codes too: repeated guesses
  -- at a closed or invented code are the signal worth seeing.
  code_entered       text not null,
  telegram_user_id   bigint not null,
  telegram_username  text,
  outcome            text not null,
  member_id          uuid references members(id),
  created_at         timestamptz not null default now(),
  constraint join_code_attempts_outcome_check check (outcome in (
    'created', 'linked',
    'unknown_code', 'revoked', 'expired', 'exhausted',
    'email_taken', 'needs_committee', 'rate_limited'
  ))
);

create index join_code_attempts_code_idx on join_code_attempts (join_code_id, created_at);
create index join_code_attempts_user_idx on join_code_attempts (telegram_user_id, created_at);

-- Admins read the log; only join_with_code() writes it (service role).
alter table join_code_attempts enable row level security;
create policy join_code_attempts_admin_select on join_code_attempts
  for select using (is_admin());

-- ---------------------------------------------------------------------------
-- join_with_code
-- ---------------------------------------------------------------------------

-- Called only by /api/store/join after it has HMAC-verified the Telegram
-- initData, so p_telegram_user_id and p_telegram_username are trusted there
-- and unchecked here -- hence service-role only, like submit_cart.
--
-- Failures are RETURNED, not raised, so the attempt row they log commits.
--
-- Matching an existing member, in order:
--   1. already bound to this Telegram id      -> already_member / inactive
--   2. the typed email belongs to a member     -> link to it, unless it is
--      bound to someone else (email_taken) or deactivated (needs_committee)
--   3. the verified handle matches an unbound member -> link to it
--   Both 2 and 3 matching DIFFERENT rows is ambiguous -> needs_committee.
--   A typed email proves nothing, so staff rows (admin/procurement) are never
--   linked this way either -> needs_committee; the bind queue handles them.
-- Otherwise a new member is created.
create function join_with_code(
  p_code text,
  p_telegram_user_id bigint,
  p_telegram_username text,
  p_full_name text,
  p_display_name text,
  p_email text
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_code_text text := upper(regexp_replace(coalesce(p_code, ''), '[^A-Za-z0-9]', '', 'g'));
  v_handle text := nullif(lower(regexp_replace(trim(coalesce(p_telegram_username, '')), '^@', '')), '');
  v_email text := nullif(lower(trim(coalesce(p_email, ''))), '');
  v_full_name text := nullif(trim(coalesce(p_full_name, '')), '');
  v_display_name text := nullif(trim(coalesce(p_display_name, '')), '');
  v_code join_codes;
  v_existing members;
  v_by_email members;
  v_by_handle members;
  v_target members;
  v_failures int;
  v_outcome text;
  v_member_id uuid;
begin
  if v_full_name is null or v_email is null then
    raise exception 'full name and email are required';
  end if;

  -- 1. Already a member. Not an attempt: the join link can reach people who
  --    joined long ago, and logging them would bury the real signal.
  select * into v_existing from members where telegram_user_id = p_telegram_user_id;
  if found then
    return jsonb_build_object(
      'outcome', case when v_existing.active then 'already_member' else 'inactive' end,
      'member_id', v_existing.id
    );
  end if;

  -- Guessing is already hopeless (31^8 codes, each open for minutes), so
  -- this is about keeping one account from flooding the log.
  select count(*) into v_failures
    from join_code_attempts
   where telegram_user_id = p_telegram_user_id
     and created_at > now() - interval '15 minutes'
     and outcome not in ('created', 'linked');

  if v_failures >= 5 then
    v_outcome := 'rate_limited';
  else
    -- Row lock: concurrent joins on one code serialise here, so the last
    -- free use cannot be taken twice.
    select * into v_code from join_codes where code = v_code_text for update;
    if not found then
      v_outcome := 'unknown_code';
    elsif v_code.revoked_at is not null then
      v_outcome := 'revoked';
    elsif v_code.expires_at <= now() then
      v_outcome := 'expired';
    elsif v_code.used_count >= v_code.max_uses then
      v_outcome := 'exhausted';
    end if;
  end if;

  if v_outcome is null then
    select * into v_by_email from members where nus_email = v_email for update;
    if v_handle is not null then
      select * into v_by_handle from members
       where telegram_username = v_handle and telegram_user_id is null
         for update;
    end if;

    if v_by_email.id is not null then
      if v_by_email.telegram_user_id is not null then
        v_outcome := 'email_taken';
      elsif not v_by_email.active
            or v_by_email.role <> 'member'
            or (v_by_handle.id is not null and v_by_handle.id <> v_by_email.id) then
        v_outcome := 'needs_committee';
      else
        v_target := v_by_email;
      end if;
    elsif v_by_handle.id is not null then
      if not v_by_handle.active or v_by_handle.role <> 'member' then
        v_outcome := 'needs_committee';
      else
        v_target := v_by_handle;
      end if;
    end if;
  end if;

  if v_outcome is null then
    if v_target.id is not null then
      -- Keep what the roster already says; fill only what it lacks. The
      -- handle is refreshed to the verified one unless another row holds it.
      update members set
        telegram_user_id   = p_telegram_user_id,
        telegram_bound_at  = now(),
        telegram_username  = case
          when v_handle is not null
               and not exists (select 1 from members o
                                where o.telegram_username = v_handle and o.id <> v_target.id)
            then v_handle
          else telegram_username end,
        nus_email          = coalesce(nus_email, v_email),
        display_name       = coalesce(display_name, v_display_name),
        notice_accepted_at = now(),
        join_code_id       = coalesce(join_code_id, v_code.id)
      where id = v_target.id;
      v_member_id := v_target.id;
      v_outcome := 'linked';
    else
      insert into members (
        full_name, display_name, nus_email, telegram_username,
        telegram_user_id, telegram_bound_at, role, active, joined_at,
        notice_accepted_at, join_code_id
      ) values (
        v_full_name, v_display_name, v_email,
        case when v_handle is not null
                  and not exists (select 1 from members o where o.telegram_username = v_handle)
             then v_handle end,
        p_telegram_user_id, now(), 'member', true, current_date,
        now(), v_code.id
      )
      returning id into v_member_id;
      v_outcome := 'created';
    end if;

    update join_codes set used_count = used_count + 1 where id = v_code.id;

    -- Anything this person left in the bind queue is now answered.
    update telegram_bind_attempts set resolved_member = v_member_id
     where telegram_user_id = p_telegram_user_id and resolved_member is null;
  end if;

  insert into join_code_attempts (
    join_code_id, code_entered, telegram_user_id, telegram_username, outcome, member_id
  ) values (
    v_code.id, left(v_code_text, 32), p_telegram_user_id, v_handle, v_outcome, v_member_id
  );

  return jsonb_build_object('outcome', v_outcome, 'member_id', v_member_id);
end;
$$;

-- `public` first: a role-specific revoke does not override the implicit
-- PUBLIC grant (the 0014 lesson).
revoke execute on function join_with_code(text, bigint, text, text, text, text)
  from public, anon, authenticated;
grant execute on function join_with_code(text, bigint, text, text, text, text)
  to service_role;
